using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HandlePlayerEnter : MonoBehaviour
{
    private Player player;
    // Start is called before the first frame update
    void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player").GetComponent<Player>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            
            player.Damage();
            Debug.Log(Heart.heart);
        }
    }
}
